# Generated by Django 5.0 on 2024-02-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_sharu'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sharu',
            table='sharu',
        ),
    ]
